### PR TITLE
fix ansible crash when editing lists, fixes #6

### LINKED ISSUE #6: Overwriting an item within a list crashes ansible
Given the list `[1, 2, 3]`, this playbook should change it to `[5, 2, 3]`.

```yml
- hosts: localhost
  gather_facts: no
  tasks:

  - copy:
      dest: /tmp/test1.yml
      content: |
        - 1
        - 2
        - 3

  - name: overwrite first entry in list
    yedit:
      src: /tmp/test1.yml
      update: yes
      key: 0  # using `index` instead of `key` yields the same result
      value: 5
```

Instead it crashes ansible:

```
TASK [overwrite first entry in list] *******************************************
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/process/result.py", line 143, in run
    elif result.is_failed():
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_result.py", line 56, in is_failed
    'results' in self._result and True in [True for x in self._result['results'] if 'failed_when_result' in x]:
TypeError: argument of type 'int' is not iterable
```

This only seems to affect lists. Overwriting a key within a dictionary works fine.

### PR DESCRIPTION
**Pull request by luto**
see #6 for details.

### CODE REVIEW

**Comment by luto** [comment]
This changes the behavior of `register`. More testing required, on how to actually return an array as a single result.

Do not merge yet.

**Comment by luto** [comment]
Since `results` is [a parameter used internally within ansible](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_result.py#L56), changing the name to `yaml` or `result` (singular) "fixes" the crash, because ansible just passes the value on without inspecting it. This is a breaking change, so I'd need your feedback on this, @kwoodson, please.

For example, in `if module.params['value']:`:

```diff
--- a/roles/lib_yaml_editor/build/ansible/yedit.py
+++ b/roles/lib_yaml_editor/build/ansible/yedit.py
@@ -127,7 +127,7 @@ def main():
             if rval[0] and module.params['src']:
                 yamlfile.write()

-            module.exit_json(changed=rval[0], results=rval[1], state="present")
+            module.exit_json(changed=rval[0], result=rval[1], state="present")

         # no edits to make
         if module.params['src']:
```

**Comment by kwoodson** [comment]
@luto,

I noticed this type of behavior in other modules that I have written.

`Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 97, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 147, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 385, in run
    play_return = strategy.run(self._iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 277, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 422, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 228, in _process_pending_results
    if task_result.is_failed():
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_result.py", line 56, in is_failed
    'results' in self._result and True in [True for x in self._result['results'] if 'failed_when_result' in x]:
`
This list comprehension in task_result.py is the issue.  Returning a single object should be fine as well.  I think the yaml like you have you in your PR should be fine.

I'll wait until I hear back.

Thanks.

**Comment by luto** [comment]
Always returning a list, results in always returning a list (surprise!). This means that the resulting fact has also has to be access as such:

```yml
  - name: set a simple value
    yedit:
      content: {}
      key: a
      value: 3
    register: out

  # nope (alright)
  - debug: var=out.a
  # nope (should work, imho)
  - debug: var=out.results.a
  # works, but has the unnecessary index. The results array will always have exactly one entry.
  - debug: var=out.results.0.a
```

I'd therefore like to switch to `result`, which would give us `out.result.a`, but breaks everything that currently access the yaml like `out.results.a`.

Note that without changing to a list or changing the name of the `results` variable, it's currently not possible to have a list as the root element of your yaml. The following, shorter sample crashes, due to the first item of `results` (the integer `3`), not being a valid result-object:

```yaml
  - name: append three to a list
    yedit:
      content: []
      append: yes
      value: 3
```

**Comment by kwoodson** [comment]
@luto, I think returning the yaml in a dict would be fine.  Or as you mentioned, changing it to result.

**Comment by luto** [comment]
I've changed the PR to reflect the new solution. The module now returns its results as `result`, instead of `results`.

```yaml
- name: append three to a list
  yedit:
    content: []
    append: yes
    value: 3
  register: out
```

```
TASK [append three to a list] **************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "out": {
        "changed": true, 
        "result": [
            3
        ], 
        "state": "present"
    }
}
```

**Pull request merged**
